- hosts: docker
  tasks:
    - name: Pull an image
      community.docker.docker_image:
        name: nginx:latest
        source: pull
    - name: deploy nginx docker container
      community.docker.docker_container:
        image: nginx:latest
        name: nginx
        state: started
        restart: yes
        ports:
          - "80:80"
    - name: Create a volume
      community.docker.docker_volume:
        name: nginx-html-volume
    - name: deploy nginx docker container with volume and ports
      community.docker.docker_container:
        image: nginx:latest
        name: nginx
        state: started
        restart: yes
        ports:
          - "80:80"
        volumes:
          - "nginx-html-volume:/var/www/html:rw"
    #- name: destroy a volume
    #  community.docker.docker_volume:
    #    name: nginx
    #    state: absent
    #- name: destroy nginx docker container
    #  community.docker.docker_container:
    #    name: nginx
    #    state: absent
...